### ISSUE TITLE
Bug - doesn't seem to work

### ISSUE THREAD

**Issue by RichardJECooke** [mhagger/git-when-merged#17]
I installed this using linuxbrew `brew install git-when-merged` and then ran

```sh
rje@ubuntut$ git log  --full-history --name-status db/migrate/20161020143200_add_franchise_group_to_parties.rb

commit 0455ddf225b61849b640065bf7ff5850ea02f8cb
Author: Richard  Cooke
Date:   Tue Oct 11 16:36:03 2016 +0200

    Fixing confirm users logic, email and styles

A       db/migrate/20161020143200_add_franchise_group_to_parties.rb

rje@ubuntut$ git when-merged 0455ddf225b61849b640065bf7ff5850ea02f8cb
refs/heads/bugfix_confirmingusers      Does not contain commit.

```

So the file is in my history, but git-when-merged tells me it's not. Why is this please?

**Comment by mhagger** [comment]
Do you have `whenmerged.default.pattern` configured? If so, it might be causing `git when-merged` to look for the commit in a different branch than the one that you are on when you run `git log`.

If that's not it, then it's a mystery to me. Is this Git repository available somewhere so that I can try to debug the problem? If not, could you perhaps anonymize the history using `git fast-export --anonymize` and push *that* history somewhere accessible?
