### ISSUE TITLE
wrong results may be returned

### ISSUE THREAD

**Issue by tao-ji** [mhagger/git-when-merged#19]
When I use 'git-when-merged' on the "k-9" (https://github.com/k9mail/k-9), I find that something may be wrong.

There is a screenshot from gitk attached, which is a part of the commits graph. 
![screenshot_20170213_095341](https://cloud.githubusercontent.com/assets/19903046/22868571/86a0e7da-f1d2-11e6-9b59-59870ee9ea83.png)

I want to find when the bottom commit is merged into the branch 'master' and I input the command "git-when-merged 15ca92414b1dfb5e365528ce9e9308296aab5085 master". However, the returned result shows that the commit is directly on this branch.  Is there something wrong?

**Comment by mhagger** [comment]
It doesn't seem wrong to me. If you follow the first parent trail from 217b5bf9f4029eb25cdfa6085836741dd1a3e076, you get to 15ca92414b1dfb5e365528ce9e9308296aab5085 after five hops. Since `git-when-merged` considers the first-parent history of a branch to be "directly on the branch", vs. commits that are only reachable by following a second or later parent link to be "merged in".

I didn't check the history more carefully, but it could be that somebody merged a branch in "backwards" of the expected order; i.e., merged master into a topic branch then fast-forwarded master to point at that merge commit. If you do stuff like that, tools like `git-when-merged` that rely on first-parent connections won't work as expected.

I'll close this issue. If I've misunderstood something, feel free to re-open.
