### ISSUE TITLE
typo in README

### ISSUE THREAD

**Issue by arielgabizon** [mhagger/git-when-merged#20]
It should be `git-when-merged` in the examples
not `git when-merged`

**Comment by mhagger** [comment]
Thanks for your feedback.

Assuming that `git` is installed [1] and that `git-when-merged` is in your `PATH` (as suggested in the "Installation" section), it should work to call `git when-merged`. What's more, that style of invoking the program has some advantages; for example, you can use `git` options like `-C` (to change directory before running the command) or `-c` (to set temporary configuration values while running the command).

The only annoying exception is that `git when-merged --help` doesn't work (because `git` tries to provide help for the subcommand itself) whereas `git-when-merged --help` does.

If you'd like to suggest adding a sentence or two to the README to make this clearer, I'd be open to considering it.

[1] As it must be, since `git-when-merged` relies on being able to run `git` commands.

**Comment by arielgabizon** [comment]
I have `git` installed and I added to `PATH`, but still, the `git-when-merged` syntax didn't work for me; and `git when-merged` did work.

**Comment by mhagger** [comment]
> I have `git` installed and I added to `PATH`, but still, the `git-when-merged` syntax didn't work for me; and `git when-merged` did work.

OK, so `git when-merged` works now? That's good.

But `git-when-merged` doesn't work? What operating system are you using?

**Comment by arielgabizon** [comment]
ubuntu . the other way round - only `git-when-merged` works

**Comment by mhagger** [comment]
Normally, when you run `git foo` it looks for a program in the `PATH` called `git-foo` and runs it. The exception I know about is that if you run `git foo --help` (and maybe `git foo -help`?) then instead of running the command, it tries to generate help for the command by running `man git-foo`.

I don't know why that is not working for you. Could it be that your `git` command is actually a shell script wrapper or something? Can you run other commands via the `git foo` mechanism?
